language: swift
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilE3Kit.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilE3Kit iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilE3Kit macOS"
    - TVOS_FRAMEWORK_SCHEME="VirgilE3Kit tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="VirgilE3Kit watchOS"
    - IOS_TEST_SCHEME="E3Kit TestApp iOS"
    - TVOS_TEST_SCHEME="E3Kit TestApp tvOS"
    - IOS_SDK=iphonesimulator12.0
    - MACOS_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.0
    - WATCHOS_SDK=watchsimulator5.0
    - FRAMEWORK_NAME=VirgilSDKKeyknox

  matrix:
    - DESTINATION="OS=12.0,name=iPhone SE"            SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"        TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="iOS"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$IOS_TEST_SCHEME"    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="NO"
    - DESTINATION="arch=x86_64"                       SCHEME="$MACOS_FRAMEWORK_SCHEME"      SDK="$MACOS_SDK"      TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="Mac"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME=""                    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="YES"    POD_LIB_LINT="NO"    SWIFT_LINT="NO"
    - DESTINATION="OS=12.0,name=Apple TV 4K"          SCHEME="$TVOS_FRAMEWORK_SCHEME"       SDK="$TVOS_SDK"       TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="tvOS"       RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$TVOS_TEST_SCHEME"   PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="YES"
    - DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm"    SCHEME="$WATCHOS_FRAMEWORK_SCHEME"    SDK="$WATCHOS_SDK"    TWO_STEP_BUILD_ENABLED="NO"     CARTHAGE_PLATFORM_NAME="watchOS"    RUN_TESTS="NO"     ADDITIONAL_TESTS_SCHEME=""                    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="YES"   SWIFT_LINT="NO"

before_install:
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - mkdir Tests/Data
  - openssl aes-256-cbc -K $encrypted_a7b6c41d0d44_key -iv $encrypted_a7b6c41d0d44_iv -in TestConfig.plist.enc -out Tests/Data/TestConfig.plist -d

  - carthage version
  - carthage bootstrap --no-build

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi
  
  - |
    if [ $TWO_STEP_BUILD_ENABLED == "YES" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
      # Build Framework in Release and Run Tests if specified
      if [ $RUN_TESTS == "YES" ]; then
        if [ -n "$ADDITIONAL_TESTS_SCHEME" ]; then
          xcodebuild -verbose -project "$PROJECT" -scheme "$ADDITIONAL_TESTS_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean test;
        else
          xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean test;
        fi
      fi
    else
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
    fi
